### PR TITLE
Add Jest, rewrite test as Jest

### PR DESCRIPTION
**Pull request by djmetzle**
And run Jests during build.

qa_req 0 (just pass the tests, err, test).

CC @andyg0808

### CODE REVIEW

**Comment by djmetzle** [comment]
Oh, ya know, this wont pass CI (Node 6 :grimacing:) until https://github.com/iFixit/node-markup/pull/65 is merged.

**Review by jarstelfox — DISMISSED** [review]
CR 🌵

**Comment by djmetzle** [comment]
Oh my. I'll need a separate PR here. I thought i'd checked in that branch converting the test to Jest already.
See: https://github.com/iFixit/node-markup/commit/93460d564eac6229030deb23bd8367b145b0b418

---

Actually, shoot, that's one commit. I'll just cherry-pick that in!

**Review by jarstelfox — CHANGES_REQUESTED** [review]
dev_block 🌵 I suspect your test no longer thinks it has jest considering the style issues. I suspect this would be solved with some `jest --init` or a change to the jest config

**Comment by djmetzle** [comment]
The plot thickens. Looks like we need a jest plugin for Eslint?
https://www.npmjs.com/package/eslint-plugin-jest

**Comment by djmetzle** [comment]
un_dev_block :shipit:

Sorry about the force push. I gave using the eslint jest plugin the college try, but its tricksy with `npx` in actions. A full `npm install` doesnt work on Actions either because we need system libraries for image manipulation (cairo, pango) that do not install correctly in the actions context. For now, i dont mind explicity Jest global imports, until this is in a better state.

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Nice!

**Review by hcutrone — APPROVED** [review]
CR :burrito:

**Pull request merged**
