### PR TITLE
Fix Fabric.js git reference

### PR DESCRIPTION
**Pull request by djmetzle**
We've merged `ifixit-production` into master on Fabric.js here:
https://github.com/iFixit/fabric.js/pull/1

This repo no longer builds correctly from the `ifixit-production` branch. We need to ref master now.

CC @andyg0808 @danielbeardsley

### CODE REVIEW

**Comment by danielbeardsley** [comment]
CR 👍 


Thanks!

**Comment by andyg0808** [comment]
CR :+1: through 6a57ccf
Nice!

**Comment by djmetzle** [comment]
Just to be clear, this merge is going to integrate the Fabric.js master changes for the main app.

**Comment by danielbeardsley** [comment]
I don't think it will change that (might be mistaken) for two reasons:

* We recently updated `master` to point just where `ifixit-production` is (so they should be nearly the same commit)
* We actually install the version of Fabric that our app points to and use that:
   https://github.com/iFixit/server-templates/blob/master/specific/base/startup-scripts/install-node-markup-dependencies#L24

**Comment by djmetzle** [comment]
@danielbeardsley 

>  don't think it will change that (might be mistaken) for two reasons:

> We recently updated master to point just where ifixit-production is (so they should be nearly the same commit)
> We actually install the version of Fabric that our app points to and use that:
> https://github.com/iFixit/server-templates/blob/master/specific/base/startup-scripts/install-node-markup-dependencies#L24

You linked the right code...
https://github.com/iFixit/server-templates/blob/4cf1820e9e87d0a1f0a05e198e9ff1e20335294d/specific/base/startup-scripts/install-node-markup-dependencies#L16-L25

This is going to integrate the changes from the fabric.js bump into base. Which is arguably a more dangerous...

The point being that https://github.com/iFixit/ifixit/pull/35039 isn't QA or merged yet. The version the app is installing is in fact different.

**Comment by djmetzle** [comment]
deploy_block :stop_sign: 

Lets merge after https://github.com/iFixit/ifixit/pull/35039

**Comment by djmetzle** [comment]
un_deploy_block :shipit: 

https://github.com/iFixit/ifixit/pull/35039 is merged. Merging this...

**Pull request merged**
