### PR TITLE
Run run-tests.py through 2to3

### PR DESCRIPTION
**Pull request by djmetzle**
Ref: https://www.pythonconverter.com/

Ref: 

CC @danielbeardsley

### CODE REVIEW

**Comment by jarstelfox** [comment]
CR 🌵 changes look sane

**Comment by andyg0808** [comment]
CR :+1: through 3bd67c4

**Comment by djmetzle** [comment]
Is running that script suppposed to return zero?

**Comment by danielbeardsley** [comment]
> Is running that script suppposed to return zero?

Yes. I noticed on F32 that it was not cause it was comparing two strings with different encodings (even though their content was the same).

**Comment by andyg0808** [comment]
CR :+1: through 0e9d8d2

**Comment by andyg0808** [comment]
Python 3 introduced the whole Binary/String distinction, IIRC. It's totally possible that the command is returning a binary and the thing it's comparing to is a string. Looks like either of these should work to get real strings out (note that `b'anbc'` is a binary, rather than a string):
```python
>>> b'anbc'.decode()
'anbc'
>>> str(b'anbc', encoding="utf-8")
'anbc'
```

**Comment by djmetzle** [comment]
Okay. Wat. The test is failing on master.

**Comment by djmetzle** [comment]
```
 DEV  [djmetzle@cominor node-markup ] (2to3) $ ./run-tests.py                                  
9900CC: Comparison string processing failed                                                    
9900CC: Image difference error = 24453.9                                                       
00CC00: Comparison string processing failed                                                    
00CC00: Image difference error = 17375.9                                                       
66CCFF: Comparison string processing failed                                                    
66CCFF: Image difference error = 46480.9                                                       
000066: Comparison string processing failed                                                    
000066: Image difference error = 8844.7                                                        
993333: Comparison string processing failed                                                    
993333: Image difference error = 17206.6                                                       
 DEV  [djmetzle@cominor node-markup ] (2to3) $ ./run-tests.py  > branch 2>&1                   
 DEV  [djmetzle@cominor node-markup ] (2to3) $ fs master                                       
> git checkout "master"                                                                        
Switched to branch 'master'                                                                    
Your branch is up to date with 'origin/master'.                                                
> cd /mnt/ebs/home/djmetzle/Work/node-markup && git submodule --quiet update --init --recursive
 DEV  [djmetzle@cominor node-markup ] (master) $ ./run-tests.py  > master 2>&1                 
 DEV  [djmetzle@cominor node-markup ] (master) $ diff master branch
 DEV  [djmetzle@cominor node-markup ] (master) $                   
```

Okay, this patch gets us back to failing just like master does. :roll_eyes:

**Comment by andyg0808** [comment]
CR :+1: through 8f49ee2

**Comment by danielbeardsley** [comment]
>  failing just like master does.

It doesn't fail when I run it:

image

**Comment by danielbeardsley** [comment]
Oh...  Looks like we run off the `ifixit-production` branch.

**Comment by danielbeardsley** [comment]
master has one extra commit that's small:
```
▶  git diff origin/ifixit-production...origin/master
diff --git package.json package.json
index 3c351f3..30ac34c 100644
--- package.json
+++ package.json
@@ -20,9 +20,9 @@
   "dependencies"    : {
     "fabric"      : "git://github.com/iFixit/fabric.js.git#ifixit-production"
    ,"jsdom"       : "0.5.6"
-   ,"xmldom"      : ">= 0.1.13"
+   ,"xmldom"      : ">=0.1.13"
    ,"optimist"    : "git://github.com/substack/node-optimist.git"
-   ,"gm"          : ">= 1.8.1"
+   ,"gm"          : ">=1.8.1"
   },
   "version"         : "0.0.2"
 }
```

I'll merge ifixit-production into master. We can call `master` the new normal.

**Comment by danielbeardsley** [comment]
QA 👍 

image

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by djmetzle** [comment]
CR :gear: Lets merge it

**Comment by danielbeardsley** [comment]
It's ben merged into master!

**Pull request closed without merging**
